// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfmGA8INFjcdWAUUyjVaX7p74_SPRSn9g',
    appId: '1:138985801012:web:3f6e78961c8978a719d161',
    messagingSenderId: '138985801012',
    projectId: 'projectpabii-kelompok4',
    authDomain: 'projectpabii-kelompok4.firebaseapp.com',
    databaseURL: 'https://projectpabii-kelompok4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projectpabii-kelompok4.firebasestorage.app',
    measurementId: 'G-YTCJ205QB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA34Q91K0AMQmYlHkPjI0bCy-XJnmQm5E',
    appId: '1:138985801012:android:8502042ad6615cc719d161',
    messagingSenderId: '138985801012',
    projectId: 'projectpabii-kelompok4',
    databaseURL: 'https://projectpabii-kelompok4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projectpabii-kelompok4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwr22fYISn093xBbz6kJ95yYtgbR61eqA',
    appId: '1:138985801012:ios:7fdd1534b2af5c2619d161',
    messagingSenderId: '138985801012',
    projectId: 'projectpabii-kelompok4',
    databaseURL: 'https://projectpabii-kelompok4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projectpabii-kelompok4.firebasestorage.app',
    iosBundleId: 'com.example.sedekahpointKelompok4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwr22fYISn093xBbz6kJ95yYtgbR61eqA',
    appId: '1:138985801012:ios:7fdd1534b2af5c2619d161',
    messagingSenderId: '138985801012',
    projectId: 'projectpabii-kelompok4',
    databaseURL: 'https://projectpabii-kelompok4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projectpabii-kelompok4.firebasestorage.app',
    iosBundleId: 'com.example.sedekahpointKelompok4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfmGA8INFjcdWAUUyjVaX7p74_SPRSn9g',
    appId: '1:138985801012:web:3c41afd1553327fc19d161',
    messagingSenderId: '138985801012',
    projectId: 'projectpabii-kelompok4',
    authDomain: 'projectpabii-kelompok4.firebaseapp.com',
    databaseURL: 'https://projectpabii-kelompok4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projectpabii-kelompok4.firebasestorage.app',
    measurementId: 'G-VKRDNEEHFZ',
  );
}
